### ISSUE TITLE
quick question on login callback

### ISSUE THREAD

**Issue by user1020** [ditesh/node-poplib#10]
Thanks Ditesh for creating this module. 

In your example,  I saw 
      client.login(username, password);
wonder if there is a callback that fires when login is successful?

thanks in advance

**Comment by ditesh** [comment]
You should get a login event on successful login, e.g.:

``` javascript
client.on("login", function(status, rawdata) {

    if (status) {

        console.log("LOGIN/PASS success");
        client.list();

    } else {

        console.log("LOGIN/PASS failed");
        client.quit();

    }
});
```

**Comment by user1020** [comment]
Thanks Ditesh.  I should have read the document a little more carefully.
