### ISSUE TITLE
Some minor issues on documentation

### ISSUE THREAD

**Issue by user1020** [ditesh/node-poplib#11]
I love this module, it helped me in my project.   Thanks Ditesh.  

There are some minor issues on the documentation: 

In the main page:

```
var POP3Client = require("node-poplib");
```

Should be 

```
var POP3Client = require("poplib");
```

The following doesn't seem to work.

```
client.auth(username, password);
```

This line works

```
client.login(username, password);
```

**Comment by ditesh** [comment]
Thanks mate!
