### ISSUE TITLE
Syntax error: Unexpected token

### ISSUE THREAD

**Issue by giuliomoro** [ditesh/node-poplib#12]
version:
poplib@0.1.6 node_modules/poplib
└── optimist@0.6.1 (minimist@0.0.8, wordwrap@0.0.2)

When running
node demos/demo.js --host pop.gmail.com --port 995 --username user@gmail.com --password potato --tls on --debug on --networkdebug on

I get

/home/giulio/FezzeeCorp/zapnode/node_modules/poplib/main.js:292
        });
        ^
SyntaxError: Unexpected token }

**Comment by Engelbrite** [comment]
```
           if (tlssock.authorized === false && 
                self.data["ignoretlserrs"] === false)
                    self.emit("tls-error", tlssock.authorizationError);

        }
    }); // should be changed to ); remove the curly brace on line 292

    socket = tlssock;
```

**Comment by ditesh** [comment]
Thanks, I'll look at it shortly.
