### ISSUE TITLE
how to retrive mails according to folder

### ISSUE THREAD

**Issue by ScorpioKing** [ditesh/node-poplib#14]
Hi Sir,
How can we retrieve all mails in a perticular mailbox folder like inbox,sent,drafts using node-poplib? What i observe is client.list() gives mails from inbox only if i am not wrong. How can i retrieve mail from sent or drafts folder.??

**Comment by ditesh** [comment]
You will need to use an IMAP4 client.

The POP3 protocol doesn't support this.
