### ISSUE TITLE
Pop Mail Fetching Issue

### ISSUE THREAD

**Issue by Anuja25** [ditesh/node-poplib#15]
I am trying to fetch  mails using pop list and retrieve listener . Sometimes i am getting all mails and sometimes i am getting particular mails from inbox.

**Comment by ditesh** [comment]
My best guess would be that this is an issue with the server itself.

You can manually telnet in and issue the LIST command after authentication and see whether the server response changes.

**Comment by Anuja25** [comment]
I want  to access mail contents such as to,from,subject,body etc.When i retrieve a particular mail by its id i got a text response. From this response how  can i access those particular fields??

**Comment by sachiniec** [comment]
@Anuja25 you can use mailparser module which results in formatted header and html fields .
