### ISSUE TITLE
Any quick example for headers parsing?

### ISSUE THREAD

**Issue by beshur** [ditesh/node-poplib#17]
Hi.

Maybe anyone has a simple example what can be done to the results of `retr` to actually work with the emails?

Thanks.

**Comment by Sjonnie2nd** [comment]
Hi Beshur,

POP3 is a relative simple and stable protocol to retrieve emails. 
What to do afterwards with the retrieved emails is far from simple and a bit off-topic here. 

Best first step is to save it in a database (in my case: MongoDB) and do nothing with it until the POP3 connection has finished.

Then if you want to view the received emails it gets lots more complicated: How to handle multipart/alternative plain text and html parts. How to handle (inline) attachments. How to handle malformed emails, etc..
I would suggest to take a look at the node MailParser library built by Andris Reinman: https://github.com/andris9/mailparser.

Greetings.

**Comment by beshur** [comment]
Thanks for reply, @Sjonnie2nd.

I've already started looking on `mailparser`, but decided to keep it a bit off for now.
