### ISSUE TITLE
Invalid auth type

### ISSUE THREAD

**Issue by rohit-saharan** [ditesh/node-poplib#2]
Am getting Invalid auth type to whichever pop3 server i try on. I have tried on my personal pop3 server, and gmail's pop. I can login to my pop3 server using telnet commands, but the retrieve-all.js script doesn't somehow work. node version is 0.6.11.

Thanks.

**Comment by ditesh** [comment]
Could you provide some debugging output? Eg can you tell me the output of

``` bash
$ node demos/demo.js --host pop.gmail.com --port 995 --username user@gmail.com --password potato --tls on --debug on --networkdebug on
```

**Comment by jefersonsv** [comment]
Hello ditesh,

I have the same proxy. see output.

Server: '+OK mail.my-provider.com a11b290a-4c98-18b3-a431-45a4a4bbe29f@mail.my-provider.com\r\n'
CONNECT success
LOGIN/PASS failed
Client: 'QUIT\r\n'
Server: '+OK POP3 server signing off\r\n'
QUIT success

My username and password it´s correct.

Can you help me?
Thanks
