### ISSUE TITLE
tried to use the sample with GMail and GoDaddy - msgnumber continues to be null

### ISSUE THREAD

**Issue by mikebz** [ditesh/node-poplib#5]

**Comment by meteormatt** [comment]
At my side, it is OK.
But too much Email when execute this line

``` javascript
client.top(123123, 10);
```

![1](https://f.cloud.github.com/assets/424475/540257/c1cd2704-c1e5-11e2-8015-1f16d5f46e8e.jpg)

**Comment by ditesh** [comment]
Hey,

I checked with gmail and its working correctly.

As for msgnumber 123123 not being found, that was a test msgnumber in demo.js. If you are changing it, you may do so but be careful as the demo will delete the msgnumber!
