### ISSUE TITLE
Not able to fetch mail other than inbox folder email .

### ISSUE THREAD

**Issue by kharatps02** [ditesh/node-poplib#8]
Hi Ditesh  ,
 I'm fetching email using list method of client after successful connection with pop3 server (pop3.live.com) .getting only inbox folder mail. 
Is there any way to get mail from other folders like sent,draft,trash etc ?

Thanks,
Popat

**Comment by ditesh** [comment]
Hey,

I am not familiar with live.com POP server. I would guess to get the other folders, you will need to use IMAP.
